# ===== THEME =====
include themes/noctalia.conf

# ===== FONT =====
font_family "JetBrainsMono Nerd Font"
font_size 11.0
font_features JetBrainsMonoNF-Regular +liga +calt
font_features JetBrainsMonoNF-Bold +liga +calt
font_features JetBrainsMonoNF-Italic +liga +calt
font_features JetBrainsMonoNF-BoldItalic +liga +calt

# ===== WINDOW =====
window_padding_width 2 4
hide_window_decorations yes
background_opacity 0.75

# ===== CURSOR =====
cursor_shape beam
cursor_blink_interval 0.5

# ===== SCROLLBACK & MOUSE =====
scrollback_lines 100000
mouse_hide_wait -1

# ===== SHELL INTEGRATION =====
shell_integration enabled

# ===== MISC QOL =====
copy_on_select clipboard
confirm_os_window_close 0

# ===== SPLIT & TAB =====
enabled_layouts splits

map ctrl+shift+d launch --location=vsplit
map ctrl+shift+e launch --location=hsplit
map ctrl+shift+w close_window
map ctrl+shift+t new_tab
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
