font_family            ComicShannsMono Nerd Font
font_size 11.0
background_opacity     0.6
cursor_trail           1
window_padding_width   10
grapheme_shaping       no

# Auto-copy: salin ke clipboard saat teks diseleksi (drag), seperti Ghostty
copy_on_select         clipboard
strip_trailing_spaces  smart

include themes/noctalia.conf
