# RakuOS-Hyprland custom tweaks

# vm.max_map_count — prevent AAA Proton game crashes during loading
# (games need many memory-mapped regions, default kernel too low)
vm.max_map_count=2147483642

# user.max_user_namespaces — support multiple simultaneous Distrobox/Podman
# rootless containers without hitting the limit
user.max_user_namespaces=28633
