color0 #4f4533
color1 #ffb4ab
color2 #ffce67
color3 #e4c281
color4 #c3e15e
color5 #fabd21
color6 #e4c281
color7 #ece1d1
color8 #9c8f79
color9 #ffb4ab
color10 #ffce67
color11 #e4c281
color12 #c3e15e
color13 #fabd21
color14 #e4c281
color15 #ece1d1

cursor                #ece1d1
cursor_text_color     #000000
background            #000000
foreground            #ece1d1
selection_foreground  #d3c5ac
selection_background  #4f4533
active_border_color   #ffce67
inactive_border_color #413726
url_color             #ffce67

active_tab_foreground   #402d00
active_tab_background   #ffce67
inactive_tab_foreground #d3c5ac
inactive_tab_background #413726
cursor_trail_color      #d3c5ac
